# Generated by Django 5.0.6 on 2024-07-02 15:11

import authentication.models.User
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=authentication.models.User.user_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
