# Generated by Django 5.0.6 on 2024-07-24 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='TDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='3D Model Name')),
                ('description', models.TextField(verbose_name='3D Model Description')),
                ('scaling', models.JSONField(default={'x': 0.0, 'y': 0.0, 'z': 0.0})),
                ('rotation', models.JSONField(default={'x': 0.0, 'y': 0.0, 'z': 0.0})),
                ('translation', models.JSONField(default={'x': 0.0, 'y': 0.0, 'z': 0.0})),
                ('color', models.JSONField(default={'alpha': 1.0, 'x': 0.0, 'y': 0.0, 'z': 0.0})),
            ],
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Texture Name')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('td_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project_2_backend_api.tdmodel')),
                ('url', models.FileField(upload_to='objects/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_2_backend_api.category')),
            ],
        ),
        migrations.AddField(
            model_name='tdmodel',
            name='textures',
            field=models.ManyToManyField(to='project_2_backend_api.texture'),
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='objects/images/')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_2_backend_api.object')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('td_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project_2_backend_api.tdmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_2_backend_api.room'),
        ),
    ]
