# Generated by Django 5.0.6 on 2024-07-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_2_backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='3D Model Description'),
        ),
        migrations.AlterField(
            model_name='tdmodel',
            name='textures',
            field=models.ManyToManyField(null=True, to='project_2_backend_api.texture'),
        ),
    ]
